# https://raps-with-r.dev/repro_cont.html

# Windows: your docker file name should be "Dockerfile"!!!

# stating that it’s based on the Ubuntu Jammy (so version 22.04) operating system
FROM ubuntu:jammy

# run command: prints the Linux kernel version from that particular Ubuntu release
RUN uname -a

# now, we need to build this image to run a container. 
# Open a terminal/command prompt in the folder where the Dockerfile is and type the following:
# owner@localhost ➤ docker build -t raps_hello .

# Where are Docker Images Stored?
# Windows:
# C:\ProgramData\DockerDesktop